version: '3.7'

services:

  template-spring-rest-production:
    container_name: template-spring-rest-production
    image: template-spring-rest:prod
    build:
      context: .
    ports:
      - '80:8080' # Spring Boot
      - '8082:8081' # Remote debug
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_HOST: template-production-db
    depends_on:
      - template-production-db

  template-production-db:
    container_name: template-production-db
    image: postgres:15.2-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PORT: ${DATABASE_PORT}
    volumes:
      - template-production-db-vol:/var/lib/postgres/data

volumes:
  template-production-db-vol:
